name: Compile thesis
on:
  push:
    branches:
      - main

jobs:
  compile:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Enable nomencl
        run: cat .latexmkrc >> $HOME/.latexmkrc
      - name: Package the thesis
        uses: georgejkaye/latex-packager@v1.0
        with:
          input-dir: .
          main: main
          project-name: thesis
      - name: Set release name
        id: name
        run: echo "name=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_OUTPUT
      - name: Create a new release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Latest draft
          tag_name: ${{ steps.name.outputs.name }}
      - name: Upload paper to the release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: main.pdf
          asset_name: main-${{ steps.name.outputs.name }}.pdf
          asset_content_type: pdf
      - name: Upload the zip to the release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: thesis.zip
          asset_name: ${{ github.event.repository.name }}-${{ steps.name.outputs.name }}.zip
          asset_content_type: zip
      - name: Delete older releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload stats to the server
        uses: georgejkaye/latex-stats-uploader@v1.1
        with:
          main: main.tex
          sha: ${{ github.sha }}
          datetime: ${{ github.event.head_commit.timestamp }}
          endpoint: ${{ vars.TRACKER_API }}
          user: ${{ vars.TRACKER_USER }}
          password: ${{ secrets.TRACKER_PASSWORD }}
